### ISSUE TITLE
Store updates reach the server late

### ISSUE THREAD

**Issue by ziyafenn** [includable/react-native-check-version#3]
Hi again. I pushed an update to the play store and after 2 hours the updated data still didn't reach the server. It was still showing the data from the previous version.

I wanted to use this lib to force update the app but with this issue it is impossible.

**Comment by tschoffelen** [comment]
Currently, our server has a 12-hour cache to prevent overloading Google Play and iTunes with requests.

We could potentially lower that. What would be the largest minimum interval that you would need?

**Comment by ziyafenn** [comment]
1 minute 🤓  
As i said i use force update. So when it is not quick, users that have already updated the app basically are deadlocked, because they will always see the force update screen.

I guess you can just update the readme and add the server update time and warn users that is not suitable for the force update :)

Thanks.

**Comment by tschoffelen** [comment]
You could very easily adapt the [webservice component](https://github.com/includable/react-native-check-version/tree/master/server) located in this repo to not cache the output of Google Play and iTunes and deploy it yourself. I think this is indeed not something we're going to support, since it would create problems with rate limits down the road.

Just out of curiosity, what is your use case for forcing updates that stringently?
